# Generated by Django 6.0.3 on 2026-03-07 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NDVIVegIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('index_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentROI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('cost_labor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_treatments', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_equipment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('roi_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
